config/routes.rb
Rails.application.routes.draw do
  root "searches#show"
  devise_for :users

  resource :search, only: [:show,:create]
  resources :tickets, except: [:edit, :update]

  namespace :admin do
    root "homes#index"
    resource :search, only: [:show,:create]

    resources :trains do
      resources :carriages, shallow: true
    end

    resources :railway_stations do
      patch :update_position, on: :member
      patch :set_times, on: :member
    end

    resources :routes
    resources :tickets
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes
  has_many :trains, foreign_key: :current_station_id

  # scope :ordered, -> { joins(:railway_stations_routes).order('railway_stations_routes.position').uniq }
  scope :ordered, lambda {
    select('railway_stations.*, railway_stations_routes.position')
      .joins(:railway_stations_routes)
      .order('railway_stations_routes.position')
      .distinct
  }

  def update_position(route, position)
    station_route = station_route(route)
    station_route&.update(position: position)
  end

  def position_in(route)
    station_route(route).try(:position)
  end

  def set_time(route, arr_time, dep_time)
    station_route = station_route(route)
    station_route&.update(arrival_time: arr_time)
    station_route&.update(departure_time: dep_time)
  end

  def time_in(route, time)
    station_route(route).try(time)&.strftime('%H:%M')
  end

  protected

  def station_route(route)
    @station_route ||= railway_stations_routes.find_by(route: route)
  end
end

app/controllers/admin/railway_stations_controller.rb
class Admin::RailwayStationsController < Admin::BaseController
  before_action :set_railway_station, only: [:show, :edit, :update, :destroy, :update_position, :set_times]

  def index
    @railway_stations = RailwayStation.all
  end

  def show
  end

  def new
    @railway_station = RailwayStation.new
  end

  def edit
  end

  def create
    @railway_station = RailwayStation.new(railway_station_params)
    if @railway_station.save
      redirect_to [:admin, @railway_station], notice: 'Railway station was successfully created.'
    else
      render :new
    end
  end

  def update
    if @railway_station.update(railway_station_params)
      redirect_to [:admin, @railway_station], notice: 'Railway station was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @railway_station.destroy
    redirect_to admin_railway_stations_url, notice: 'Railway station was successfully destroyed.'
  end

  def update_position
    @route = Route.find(params[:route_id])
    @railway_station.update_position(@route, params[:position])
    redirect_to [:admin, @route]
  end

  def set_times
    @route = Route.find(params[:route_id])
    @railway_station.set_time(@route, params[:arrival_time], params[:departure_time])
    redirect_to [:admin, @route]
  end

  private

  def set_railway_station
    @railway_station = RailwayStation.find(params[:id])
  end

  def railway_station_params
    params.require(:railway_station).permit(:name)
  end
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/views/admin/railway_stations/_form.html.slim
= form_for [:admin, railway_station] do |f|
  = render 'common/errors', resource: railway_station
  .input-group
    span.input-group-addon
      | Title
    = f.text_field :name, class: 'form-control'
  br
  .actions
    = f.submit

app/views/admin/railway_stations/_railway_station.html.slim
tr
  td
    = railway_station.name
  td
    = link_to 'Show', [:admin, railway_station], class: 'btn btn-default'
    = link_to 'Edit', edit_admin_railway_station_path(railway_station), class: 'btn btn-primary'
    = link_to 'Destroy', [:admin, railway_station], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

app/views/admin/railway_stations/edit.html.slim
h3
  | Editing Railway Station
= render 'form', railway_station: @railway_station
= link_to 'Show', [:admin, @railway_station], class: 'btn btn-default'
= link_to 'Back', admin_railway_stations_path, class: 'btn btn-default'

app/views/admin/railway_stations/index.html.slim
h3
  | Railway Stations
table.table.table-bordered
  thead
    tr
      th
        | Name
      th
  tbody
    = render @railway_stations
= link_to 'New Railway Station', new_admin_railway_station_path, class: 'btn btn-primary'

app/views/admin/railway_stations/new.html.slim
h3
  | New Railway Station
= render 'form', railway_station: @railway_station
= link_to 'Back', admin_railway_stations_path

app/views/admin/railway_stations/show.html.slim
p
  strong
    | Name:
  = @railway_station.name
= link_to 'Edit', edit_admin_railway_station_path(@railway_station)
|  | 
= link_to 'Back', admin_railway_stations_path