config/routes.rb
Rails.application.routes.draw do
  root "searches#show"
  devise_for :users

  resource :search, only: [:show,:create]
  resources :tickets, except: [:edit, :update]

  namespace :admin do
    root "homes#index"
    resource :search, only: [:show,:create]

    resources :trains do
      resources :carriages, shallow: true
    end

    resources :railway_stations do
      patch :update_position, on: :member
      patch :set_times, on: :member
    end

    resources :routes
    resources :tickets
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/route.rb
class Route < ApplicationRecord
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes
  has_many :trains

  validates :railway_station_ids, presence: true

  before_create :set_name

  private

  def set_name
    self.name = "#{railway_stations.first.name} - #{railway_stations.last.name}"
  end
end

app/controllers/admin/routes_controller.rb
class Admin::RoutesController < Admin::BaseController
  before_action :set_route, only: [:show, :edit, :update, :destroy]
  def index
    @routes = Route.all
  end

  def show
  end

  def new
    @route = Route.new
  end

  def edit
  end

  def create
    @route = Route.new(route_params)
    if @route.save
      redirect_to [:admin, @route], notice: 'Route was successfully created!'
    else
      render :new
    end
  end

  def update
    if @route.update(route_params)
      redirect_to admin_routes_path, notice: 'Route was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to admin_routes_url, notice: 'Route was successfully destroyed!'
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:name, railway_station_ids: [])
  end
end

app/views/admin/routes/_form.html.slim
= form_for [:admin, route] do |f|
  = render 'common/errors', resource: route
  .form-group
    = f.label :railway_station_ids
    = f.collection_select :railway_station_ids, RailwayStation.all, :id, :name, {}, { multiple: true, class: 'form-control'}
  .actions
    = f.submit t('.submit', action: @route.new_record? ? 'Содать' : 'Изменить')

app/views/admin/routes/_name_form.html.slim
= form_for [:admin, route], html: { style: 'display: none', class: 'form-inline' } do |f|
  .form-group
    = f.text_field :name, class: 'form-control'
    = f.button t('.submit'), class: 'btn btn-primary'

app/views/admin/routes/edit.html.slim
h3
  = t('.title')
= render 'form', route: @route
.form-group
= link_to t('common.show'), [:admin, @route], class: 'btn btn-default'
= link_to t('common.back'), admin_routes_path, class: 'btn btn-default'

app/views/admin/routes/index.html.slim
h3
  = t('.title')
table.table.table-bordered
  thead
    tr
      th
        = t('.names')
      th
  tbody
    - @routes.each do |route|
      tr
        td
          div id=('route_id_'+"#{route.id}")
            = route.name
          = render 'name_form', route: route
          = link_to t('common.edit'), '', class: 'edit_route btn btn-link', data: { route_id: "#{route.id}"}
        td
          = link_to t('common.show'), [:admin, route], class: 'btn btn-default'
          = link_to t('common.edit'), edit_admin_route_path(route), class: 'btn btn-primary'
          = link_to t('common.destroy'), [:admin, route], method: :delete, data: { confirm: 'are_you_sure' }, class: 'btn btn-danger'
          '
= link_to t('.new_route'), new_admin_route_path, class: 'btn btn-primary'

app/views/admin/routes/new.html.slim
h3
  = t('.title')
= render 'form', route: @route
.form-group
= link_to t('common.back'), admin_routes_path, class: 'btn btn-default'

app/views/admin/routes/show.html.slim
h3
  = t('.title', name: @route.name )
table.table.table-bordered
  thead
    tr
      td
        = t('.name')
      td
        = t('.position')
      td
        = t('.action')
      td
        = t('.arrival_time')
      td
        = t('.departure_time')
      td
        = t('common.edit')
  tbody
    - if @route.railway_stations.empty?
      tr
        td
          | No stations in the route!
    - else
      - @route.railway_stations.ordered.each do |station|
        tr
          td
            = station.name
          = form_tag update_position_admin_railway_station_path(station), method: :patch do
            td
              = number_field_tag :position, station.position_in(@route)
            = hidden_field_tag :route_id, @route.id
            td
              = submit_tag "Change"
          = form_tag set_times_admin_railway_station_path(station), method: :patch do
            td
              = time_field_tag :arrival_time, station.time_in(@route, :arrival_time )
            td
              = time_field_tag :departure_time, station.time_in(@route, :departure_time)
            = hidden_field_tag :route_id, @route.id
            td
              = submit_tag '✓'
strong
  = t('.trains')
ul
  - if @route.trains.empty?
    |  No trains in the route! 
  - else
    - @route.trains.each do |train|
      li
        = train.number
.form-group
= link_to t('common.edit'), edit_admin_route_path(@route), class: 'btn btn-default'
= link_to t('common.back'), admin_routes_path, class: 'btn btn-default'