config/routes.rb
Rails.application.routes.draw do
  root "searches#show"
  devise_for :users

  resource :search, only: [:show,:create]
  resources :tickets, except: [:edit, :update]

  namespace :admin do
    root "homes#index"
    resource :search, only: [:show,:create]

    resources :trains do
      resources :carriages, shallow: true
    end

    resources :railway_stations do
      patch :update_position, on: :member
      patch :set_times, on: :member
    end

    resources :routes
    resources :tickets
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  belongs_to :train
  belongs_to :start_station, class_name: 'RailwayStation', foreign_key: :start_station_id
  belongs_to :end_station, class_name: 'RailwayStation', foreign_key: :end_station_id

  validates :full_name, :passport, presence: true

  after_create :send_notification
  after_destroy :send_cancellation

  def route_name
    "#{start_station.name} - #{end_station.name}"
  end

  private

  def send_notification
    TicketsMailer.buy_ticket(user, self).deliver_now
  end

  def send_cancellation
    TicketsMailer.cancel_ticket(user, self).deliver_now
  end
end

app/controllers/admin/tickets_controller.rb
class Admin::TicketsController < Admin::BaseController
  before_action :authenticate_user!
  before_action :set_ticket, only: [:show, :destroy, :edit, :update]

  def index
    @tickets = Ticket.all
  end

  def show
  end

  def new
    @ticket = Ticket.new
    @train = Train.find(params[:train_id])
    @start_station = RailwayStation.find(params[:start_station_id])
    @end_station = RailwayStation.find(params[:end_station_id])
  end

  def create
    @ticket = Ticket.new(ticket_params)

    if @ticket.save
      redirect_to [:admin, @ticket]
    else
      redirect_to search_path, notice: 'Ticket not  purchased!!!'
    end
  end

  def edit
    @train = @ticket.train
    @start_station = @ticket.start_station
    @end_station = @ticket.end_station
  end

  def update
    if @ticket.update(ticket_params)
      redirect_to [:admin, @ticket], notice: 'Ticket was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @ticket.destroy
    redirect_to admin_tickets_url, notice: 'Ticket was successfully destroyed.'
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:start_station_id,
                                   :end_station_id,
                                   :train_id,
                                   :full_name,
                                   :passport,
                                   :user_id)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ticket, only: [:show, :destroy]

  def index
    @tickets = current_user.tickets
  end

  def show
  end

  def new
    @ticket = Ticket.new
    @train = Train.find(params[:train_id])
    @start_station = RailwayStation.find(params[:start_station_id])
    @end_station = RailwayStation.find(params[:end_station_id])
  end

  def create
    @ticket = current_user.tickets.new(ticket_params)

    if @ticket.save
      redirect_to ticket_path(@ticket)
    else
      redirect_to search_path, notice: 'Ticket not  purchased!!!'
    end
  end

  def destroy
    @ticket.destroy
    redirect_to tickets_url, notice: 'Ticket was successfully destroyed.'
  end

  private

  def set_ticket
    @ticket = current_user.tickets.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:start_station_id,
                                   :end_station_id,
                                   :train_id,
                                   :full_name,
                                   :passport)
  end
end

app/views/admin/tickets/_form.html.slim
.column.is-6.is-flex-mobile
  = form_for [:admin, ticket]  do |f|
    table.table.is-narrow
      tr
        th
          = f.label :user
        td
          .field
            span.select
              = f.collection_select :user_id, User.all, :id, :name
      tr
        th
          = t('.train')
        td
          = @train.number
          = f.hidden_field(:train_id, value: @train.id)
      tr
        th
          = t('.departure_station')
        td
          = @start_station.name
          = f.hidden_field(:start_station_id, value: @start_station.id) 
      tr
        th
          = t('.departure_time')
        td
          = @start_station.time_in(@train.route, :departure_time)
      tr
        th
          = t('.arrival_station')
        td
          = @end_station.name
          = f.hidden_field(:end_station_id, value: @end_station.id)
      tr
        th
          = t('.arrival_time')
        td
          = @end_station.time_in(@train.route, :arrival_time)
      tr
        th
          = t('.full_name')
        td
          = f.text_field :full_name, class: 'input'
      tr
        th
          = t('.passport')
        td
          = f.text_field :passport, class: 'input'

    = link_to "Back", admin_tickets_path, class: 'button is-primary'
    |  
    = f.button class: 'button is-info'

app/views/admin/tickets/edit.html.slim
h1.title
  = t('.ticket')
hr
= render 'form', ticket: @ticket
.form-group
= link_to 'Show', [:admin, @ticket], class: 'btn btn-default'
= link_to 'Back', admin_tickets_path, class: 'btn btn-default'

app/views/admin/tickets/index.html.slim
h1.title
  = t('.tickets')
hr
table.table.is-bordered
  thead
    tr
      td
        | Train #
      td
        | Departure
      td
        | Arrival
      td
        | User
      td
  tbody
    - @tickets.each do |ticket|
      tr
        td
          = ticket.train.number
        td
          = ticket.start_station.name
        td
          = ticket.end_station.name
        td
          = ticket.user.email
        td
          = link_to t('common.show'), [:admin, ticket], class: 'button is-primary'
          |  
          = link_to t('common.edit'), edit_admin_ticket_path(ticket), class: 'button is-warning'
          |  
          = link_to t('common.destroy'), [:admin, ticket], method: :delete, data: { confirm: 'Are you sure?' }, class: 'button is-danger'
= link_to "New Ticket", admin_search_path, class: 'button is-primary'

app/views/admin/tickets/new.html.slim
h1.title
  | New Ticket
hr
= render 'form', ticket: @ticket

app/views/admin/tickets/show.html.slim
h1.title
  | Ticket information
hr
h2.subtitle
  | Train: 
  = @ticket.train.number
h3
  | Departure from: 
  = @ticket.start_station.name
h4
  | Departure time: 
  = @ticket.start_station.time_in(@ticket.train.route, :departure_time)
hr
h3
  | Arrival to: 
  = @ticket.end_station.name
h4
  | Arrival time: 
  = @ticket.end_station.time_in(@ticket.train.route, :arrival_time)
hr
h3
  | Passenger: 
  = @ticket.full_name
h4
  | Passport: 
  = @ticket.passport
hr
= link_to t('.tickets'), admin_tickets_path, class: 'button is-primary'