config/routes.rb
Rails.application.routes.draw do
  root "searches#show"
  devise_for :users

  resource :search, only: [:show,:create]
  resources :tickets, except: [:edit, :update]

  namespace :admin do
    root "homes#index"
    resource :search, only: [:show,:create]

    resources :trains do
      resources :carriages, shallow: true
    end

    resources :railway_stations do
      patch :update_position, on: :member
      patch :set_times, on: :member
    end

    resources :routes
    resources :tickets
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/train.rb
class Train < ApplicationRecord
  has_many :tickets
  has_many :carriages, -> { order(number: :asc) }

  belongs_to :route, optional: true
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id, optional: true

  validates :number, format: { with: /[A-Z]{2}-?\d{3}/,
                               message: 'Correct format: AA-123' },
                     presence: true

  def self.find_trains_by(start_station, end_station)
    start_trains = Train.joins(route: :railway_stations).where(railway_stations: { id: start_station })
    end_trains = Train.joins(route: :railway_stations).where(railway_stations: { id: end_station })
    start_trains & end_trains
  end

  def carriages_order
    if numbering
      carriages
    else
      carriages.reverse_order
    end
  end

  def seats_sum(carriage_type, seat_type)
    carriages.where(type: carriage_type).sum(seat_type)
  end
end

app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseController
  before_action :authenticate_user!
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  def index
    @trains = Train.all
  end

  def show
  end

  def new
    @train = Train.new
  end

  def edit
  end

  def create
    @train = Train.new(train_params)
    if @train.save
      redirect_to [:admin, @train], notice: 'Train was successfully created.'
    else
      render :new
    end
  end

  def update
    if @train.update(train_params)
      redirect_to admin_trains_path, notice: 'Train was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @train.destroy
    redirect_to admin_trains_url, notice: 'Train was successfully destroyed.'
  end

  private

  def set_train
    @train = Train.find(params[:id])
  end

  def train_params
    params.require(:train).permit(:number, :route_id, :numbering)
  end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/admin/trains/_form.html.slim
= form_for [:admin, train] do |f|
  = render 'common/errors', resource: train
  .field
    = f.label t('.number'), class: 'label'
    p.control
      = f.text_field :number, class: 'input'
  .field
    = f.label t('.route'), class: 'label'
    p.control
      span.select
        = f.collection_select :route_id, Route.all, :id, :name, { include_blank: true }
  .field
    = f.label t('.numbering'), class: 'label'
    p.control
      span.select
        = f.select :numbering, [[t('.direct'), true], [t('.reverse'), false]], {}
  = f.button t('.submit', action: train.new_record? ? 'Создать' : 'Изменить'), class: 'button is-primary'

app/views/admin/trains/_number_form.html.slim
= form_for [:admin, train], html: { style: 'display: none', class: 'form-inline' } do |f|
  .field.has-addons
    p.control
      = f.text_field :number, class: 'input is-primary'
    p.control
      = f.button t('.submit'), class: 'button is-primary'

app/views/admin/trains/_train.html.slim
tr
  td[width="300px"]
    div id=("train_number_" "#{train.id}")
      = train.number
    = render 'number_form', train: train
    = link_to t('common.edit'), '', class: 'edit_train btn-xs btn-link',  data: { train_id: "#{train.id}" }
  td
    = link_to t('common.show'), [:admin, train], class: 'button is-primary'
    |  
    = link_to t('common.edit'), edit_admin_train_path(train), class: 'button is-warning'
    |  
    = link_to t('common.destroy'), [:admin, train], method: :delete, class: 'button is-danger', data: { confirm: t('common.are_you_sure') }

app/views/admin/trains/edit.html.slim
h1.title
  = t('.title')
= render 'form', train: @train
.section
= link_to t('common.show'), [:admin, @train], class: 'button is-warning'
|    
= link_to t('common.back'), admin_trains_path, class: 'button is-primary'

app/views/admin/trains/index.html.slim
h1.title
  = t('.title')
hr
table.table.is-bordered
  thead
    tr
      th
        = t('common.number')
      th[colspan="3"]
  tbody
    = render @trains
= link_to t('common.new_train'), new_admin_train_path, class: "button is-primary"

app/views/admin/trains/new.html.slim
h1.title
  = t('.title')
= render 'form', train: @train
.section 
= link_to t('common.back'), admin_trains_path, class: 'button is-primary'

app/views/admin/trains/show.html.slim
h1.title
  = t('.title', number: @train.number)
hr
h5.title.is-5
  = t('.route')
- if @train.route.present?
  h4.subtitle.is-4
    = @train.route.name
- else
  = t('common.route_not_assigned')
hr
h5.title.is-5
  = t('common.carriages')

- @train.carriages_order.each do |carriage|
  span
    = link_to "#{carriage.number}", [:admin, carriage.becomes(Carriage)], class: "button is-primary"
    |  
.section
= link_to t('common.add_carriage'), new_admin_train_carriage_path(@train), class: 'button is-primary'
|  
= link_to t('common.edit'), edit_admin_train_path(@train), class: 'button is-warning'
|    
= link_to t('common.back'), admin_trains_path, class: 'button is-primary'